name: Generate Snake Game

on:
  schedule:
    # Executa diariamente às 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite executar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.svg?palette=github-light
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9            

      - name: Commit e push da animação
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizando animação Snake 🐍"
          add: "dist/*.svg"
